# Generated by Django 5.1.1 on 2024-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('Lo', 'Low'), ('Me', 'Medium'), ('Hi', 'High')], default='-', max_length=10),
            preserve_default=False,
        ),
    ]
